/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Exceptions.PersonaYaExisteException;
import java.applet.AudioClip;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Pelicula;
import modelo.Persona;
import modelo.Silla;
import com.sun.speech.freetts.VoiceManager;
import com.sun.speech.freetts.Voice;
import modelo.ProductoComprados;


/**
 *
 * @author USUARIO
 */
public class VistaIngreso extends javax.swing.JFrame {

    VistaPrincipal vistaPrincipal;
    private int fila;
    private int columna;

    public VistaIngreso(VistaPrincipal vistaPrincipal, int fila, int columna, int numero) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        this.vistaPrincipal = vistaPrincipal;
        this.fila = fila;
        this.columna = columna;
        vistaPrincipal.setEnabled(false);
        jLabelDeshabiliarSilla.setEnabled(false);
        txtADeshabiliatSilla.setEnabled(false);
        btnGuardarArgumentoDeshabiliar.setEnabled(false);
        txtNumeroSilla.setText(String.valueOf(numero));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelSilla = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        txtNumeroSilla = new javax.swing.JTextField();
        jLabelDeshabiliarSilla = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbNombrePelicula = new javax.swing.JComboBox<>();
        jLabelNombre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtADeshabiliatSilla = new javax.swing.JTextArea();
        btnOcupar = new javax.swing.JButton();
        btnDeshabilitarSilla = new javax.swing.JButton();
        btnGuardarArgumentoDeshabiliar = new javax.swing.JButton();
        jLabelCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabelEstrenosNuevos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabelEstrenosNuevos1 = new javax.swing.JLabel();
        jLabelEstrenosNuevos2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        btnSalir.setText("REGRESAR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cinema.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 713, 280));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6355.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 30, 460));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6355.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 30, 460));

        jLabelSilla.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelSilla.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSilla.setText("Silla:");
        getContentPane().add(jLabelSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, 30));

        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 200, 30));

        jLabelApellido.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApellido.setText("Apellido:");
        getContentPane().add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 30));

        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 200, 30));

        jLabelTelefono.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTelefono.setText("Telefono:");
        getContentPane().add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 30));

        txtNumeroSilla.setEditable(false);
        txtNumeroSilla.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNumeroSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 40, 30));

        jLabelDeshabiliarSilla.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDeshabiliarSilla.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabelDeshabiliarSilla.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDeshabiliarSilla.setText("DESHABILITAR SILLA");
        getContentPane().add(jLabelDeshabiliarSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("DATOS DEL USUARIO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        cmbNombrePelicula.setForeground(new java.awt.Color(0, 0, 0));
        cmbNombrePelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contra el Demonio", "Pinocho", "Rapidos Y Furiosos 9", "El Protector" }));
        getContentPane().add(cmbNombrePelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 200, 30));

        jLabelNombre.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 200, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("!El MEJOR CINE!");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, -1, -1));

        txtADeshabiliatSilla.setColumns(20);
        txtADeshabiliatSilla.setRows(5);
        jScrollPane1.setViewportView(txtADeshabiliatSilla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 480, -1));

        btnOcupar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        btnOcupar.setText("OCUPAR");
        btnOcupar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcuparActionPerformed(evt);
            }
        });
        getContentPane().add(btnOcupar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        btnDeshabilitarSilla.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        btnDeshabilitarSilla.setText("DESHABILITAR SILLA");
        btnDeshabilitarSilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitarSillaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeshabilitarSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, 30));

        btnGuardarArgumentoDeshabiliar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        btnGuardarArgumentoDeshabiliar.setText("Guardar");
        btnGuardarArgumentoDeshabiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarArgumentoDeshabiliarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarArgumentoDeshabiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, -1, -1));

        jLabelCedula.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCedula.setText("Cedula:");
        getContentPane().add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, 30));

        txtCedula.setForeground(new java.awt.Color(0, 0, 0));
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 200, 30));

        jLabelEstrenosNuevos.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelEstrenosNuevos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstrenosNuevos.setText("Minutos");
        getContentPane().add(jLabelEstrenosNuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, 40));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("DATOS DE LA PELI");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        txtDuracion.setEditable(false);
        txtDuracion.setText("108");
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 40, -1));

        jLabelEstrenosNuevos1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelEstrenosNuevos1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstrenosNuevos1.setText("Estrenos Nuevos:");
        getContentPane().add(jLabelEstrenosNuevos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, 30));

        jLabelEstrenosNuevos2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelEstrenosNuevos2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstrenosNuevos2.setText("Duracion: ");
        getContentPane().add(jLabelEstrenosNuevos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoIngreso.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 710, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        vistaPrincipal.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validar = evt.getKeyChar();

        if (!Character.isLetter(validar) && validar != KeyEvent.VK_SPACE && validar != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char validar = evt.getKeyChar();

        if (!Character.isLetter(validar) && validar != KeyEvent.VK_SPACE && validar != KeyEvent.VK_BACK_SPACE) {
            evt.consume();

        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresa solo Numeros");
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresa solo Numeros");
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void btnOcuparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcuparActionPerformed
        if (txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() || txtCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes colocar toda la informacion");
        } else {
            try {
                String nombre = txtNombre.getText();
                String apellido = txtApellido.getText();
                int documento = Integer.parseInt(txtCedula.getText());
                String nombrePelicula = String.valueOf(cmbNombrePelicula.getSelectedItem());
                String telefono = txtTelefono.getText();
                String duracion = txtDuracion.getText();
                Pelicula pelicula = new Pelicula(nombrePelicula, duracion);
                Persona persona = new Persona(nombre, apellido, documento, pelicula, telefono, 0, 0, null);
                vistaPrincipal.controladorCRUDCine.agregarPersona(persona, fila, columna);
                JOptionPane.showMessageDialog(null, "se ha ocupado!!!");
                
                
                vistaPrincipal.controladorCRUDCine.estadoOcupada(fila, columna);
                vistaPrincipal.validarPosiciones();
                vistaPrincipal.setEnabled(true);
                this.dispose();
            } catch (PersonaYaExisteException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        }
    }//GEN-LAST:event_btnOcuparActionPerformed

    private void btnDeshabilitarSillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitarSillaActionPerformed
        txtADeshabiliatSilla.setEnabled(true);
        btnGuardarArgumentoDeshabiliar.setEnabled(true);
        jLabelDeshabiliarSilla.setEnabled(true);
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtCedula.setEnabled(false);
        txtTelefono.setEnabled(false);
        cmbNombrePelicula.setEnabled(false);
        btnOcupar.setEnabled(false);
        vistaPrincipal.controladorCRUDCine.estadoDeshabilitada(fila, columna);

    }//GEN-LAST:event_btnDeshabilitarSillaActionPerformed

    private void btnGuardarArgumentoDeshabiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArgumentoDeshabiliarActionPerformed
        if (txtADeshabiliatSilla.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes colocar la razon por la cual se deshabilita la silla");
        } else {
            String razon = txtADeshabiliatSilla.getText();
            vistaPrincipal.controladorCRUDCine.razonPorDeshabilitacion(fila, columna, razon);
            JOptionPane.showMessageDialog(null, "Se ha deshabilitado por la razon");
            vistaPrincipal.validarPosiciones();
            vistaPrincipal.setEnabled(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnGuardarArgumentoDeshabiliarActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeshabilitarSilla;
    private javax.swing.JButton btnGuardarArgumentoDeshabiliar;
    private javax.swing.JButton btnOcupar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbNombrePelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelDeshabiliarSilla;
    private javax.swing.JLabel jLabelEstrenosNuevos;
    private javax.swing.JLabel jLabelEstrenosNuevos1;
    private javax.swing.JLabel jLabelEstrenosNuevos2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSilla;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtADeshabiliatSilla;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroSilla;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
