/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Silla;

/**
 *
 * @author USUARIO
 */
public class VistaOcupada extends javax.swing.JFrame {

    VistaPrincipal vistaPrincipal;
    private int fila;
    private int columna;
    private int numero;
    Silla[][] sillas;

    public VistaOcupada(VistaPrincipal vistaPrincipal, int fila, int columna, int numero) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        this.vistaPrincipal = vistaPrincipal;
        this.fila = fila;
        this.columna = columna;
        this.numero = numero;
        vistaPrincipal.setEnabled(false);
        txtNumeroSilla.setText(String.valueOf(numero));
        sillas = new Silla[10][12];
        buscarPersona();

    }

    public final void buscarPersona() {

        for (int i = 0; i < sillas.length; i++) {
            for (int j = 0; j < sillas[i].length; j++) {
                Silla silla = vistaPrincipal.controladorCRUDCine.obtenerSilla(fila, columna);
                txtNombre.setText(silla.getPersona().getNombre());
                txtApellido.setText(silla.getPersona().getApellido());
                txtCedula.setText(String.valueOf(silla.getPersona().getDocumento()));
                txtCuentaPersonal.setText(silla.getPersona().getTelefono());
                txtPeliculaSeleccionada.setText(silla.getPersona().getPelicula().getNombrePelicula());
                txtTelefono.setText(silla.getPersona().getTelefono());
                txtCantidadCompradaPorProducto.setText(String.valueOf(silla.getPersona().getCantidadComprada()));
                txtCuentaPersonal.setText(String.valueOf(silla.getPersona().getCuentaPersonal()));

            }
        }
        int tamaño = vistaPrincipal.controladorCRUDCine.retornarTamaño(fila, columna);
        cmbProductosComprados.removeAllItems();
        for (int k = 0; k < tamaño; k++) {
            cmbProductosComprados.addItem(vistaPrincipal.controladorCRUDCine.retornarProductoComprado(fila, columna, k).getNombre());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelSilla = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtNumeroSilla = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCuentaPersonal = new javax.swing.JTextField();
        jLabelCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabelEstrenosNuevos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPeliculaSeleccionada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        jLabelTelefono1 = new javax.swing.JLabel();
        jLabelTelefono4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelTelefono2 = new javax.swing.JLabel();
        cmbProductosComprados = new javax.swing.JComboBox<>();
        jLabelTelefono3 = new javax.swing.JLabel();
        txtCantidadCompradaPorProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("!El MEJOR CINE!");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, 20));

        btnRegresar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cinema.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 713, 280));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6355.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 30, 450));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6355.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 30, 450));

        jLabelSilla.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelSilla.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSilla.setText("Silla:");
        getContentPane().add(jLabelSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, 30));

        txtNombre.setEditable(false);
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 200, 30));

        jLabelApellido.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApellido.setText("Apellido:");
        getContentPane().add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 30));

        txtApellido.setEditable(false);
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 200, 30));

        txtNumeroSilla.setEditable(false);
        txtNumeroSilla.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNumeroSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 40, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("DATOS DE COMPRAS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sillaOcupada.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        txtCuentaPersonal.setEditable(false);
        txtCuentaPersonal.setForeground(new java.awt.Color(0, 0, 0));
        txtCuentaPersonal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCuentaPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuentaPersonalKeyTyped(evt);
            }
        });
        getContentPane().add(txtCuentaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 140, 30));

        jLabelCedula.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelCedula.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCedula.setText("Cedula:");
        getContentPane().add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 30));

        txtCedula.setEditable(false);
        txtCedula.setForeground(new java.awt.Color(0, 0, 0));
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 200, 30));

        jLabelEstrenosNuevos.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelEstrenosNuevos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstrenosNuevos.setText("Pelicula Seleccionada:");
        getContentPane().add(jLabelEstrenosNuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, 30));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("           //               DATOS DE LA PELI");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        txtPeliculaSeleccionada.setEditable(false);
        txtPeliculaSeleccionada.setForeground(new java.awt.Color(0, 0, 0));
        txtPeliculaSeleccionada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPeliculaSeleccionadaKeyTyped(evt);
            }
        });
        getContentPane().add(txtPeliculaSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 200, 30));

        jButton1.setText("Comprar productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 670, 470, 40));

        txtTelefono.setEditable(false);
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 140, 30));

        jLabelTelefono1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelTelefono1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTelefono1.setText("Catidad De producto Comprados");
        getContentPane().add(jLabelTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, -1, 30));

        jLabelTelefono4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelTelefono4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTelefono4.setText("Telefono:");
        getContentPane().add(jLabelTelefono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, 30));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("DATOS DEL USUARIO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabelTelefono2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelTelefono2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTelefono2.setText("Cuenta Personal:");
        getContentPane().add(jLabelTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, 30));

        getContentPane().add(cmbProductosComprados, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 150, 30));

        jLabelTelefono3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jLabelTelefono3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTelefono3.setText("Productos Comprados:");
        getContentPane().add(jLabelTelefono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, 30));

        txtCantidadCompradaPorProducto.setEditable(false);
        txtCantidadCompradaPorProducto.setForeground(new java.awt.Color(0, 0, 0));
        txtCantidadCompradaPorProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadCompradaPorProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadCompradaPorProductoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCantidadCompradaPorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 200, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoIngreso.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 710, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        vistaPrincipal.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validar = evt.getKeyChar();

        if (!Character.isLetter(validar) && validar != KeyEvent.VK_SPACE && validar != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char validar = evt.getKeyChar();

        if (!Character.isLetter(validar) && validar != KeyEvent.VK_SPACE && validar != KeyEvent.VK_BACK_SPACE) {
            evt.consume();

        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresa solo Numeros");
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtPeliculaSeleccionadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPeliculaSeleccionadaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeliculaSeleccionadaKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VistaventaProductos vistaventaProductos = new VistaventaProductos(this, fila, columna, numero);
        vistaventaProductos.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCuentaPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaPersonalKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresa solo Numeros");
        }
    }//GEN-LAST:event_txtCuentaPersonalKeyTyped

    private void txtCantidadCompradaPorProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadCompradaPorProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadCompradaPorProductoKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbProductosComprados;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelEstrenosNuevos;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSilla;
    private javax.swing.JLabel jLabelTelefono1;
    private javax.swing.JLabel jLabelTelefono2;
    private javax.swing.JLabel jLabelTelefono3;
    private javax.swing.JLabel jLabelTelefono4;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCantidadCompradaPorProducto;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCuentaPersonal;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroSilla;
    private javax.swing.JTextField txtPeliculaSeleccionada;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
