/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Silla;

/**
 *
 * @author USUARIO
 */
public class VistaDeshabilitada extends javax.swing.JFrame {

    VistaPrincipal vistaPrincipal;
    private int fila;
    private int columna;
    Silla[][] sillas;

    public VistaDeshabilitada(VistaPrincipal vistaPrincipal, int fila, int columna, int numero) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        this.vistaPrincipal = vistaPrincipal;
        this.fila = fila;
        this.columna = columna;
        vistaPrincipal.setEnabled(false);
        txtNumeroSilla.setText(String.valueOf(numero));
        sillas = new Silla[10][12];
        for (int i = 0; i < sillas.length; i++) {
            for (int j = 0; j < sillas[i].length; j++) {
                Silla silla = vistaPrincipal.controladorCRUDCine.obtenerSilla(fila, columna);
                txtARazon.setText(silla.getRazonporDeshabilitacion());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtARazon = new javax.swing.JTextArea();
        txtNumeroSilla = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnHabilitarSilla = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Deshabilitada");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Razon:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sillaDeshabilitada.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Silla ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cabecera 2 .jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 230));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Numero Silla:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txtARazon.setEditable(false);
        txtARazon.setColumns(20);
        txtARazon.setRows(5);
        jScrollPane1.setViewportView(txtARazon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 360, 100));

        txtNumeroSilla.setEditable(false);
        getContentPane().add(txtNumeroSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 30, -1));

        btnRegresar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 260, -1));

        btnHabilitarSilla.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        btnHabilitarSilla.setText("HABILITAR SILLA");
        btnHabilitarSilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarSillaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHabilitarSilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 260, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoProductos.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 420, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        vistaPrincipal.setEnabled(true);
        this.dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnHabilitarSillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarSillaActionPerformed
        vistaPrincipal.controladorCRUDCine.estadoDisponible(fila, columna);
        vistaPrincipal.validarPosiciones();
        vistaPrincipal.setEnabled(true);
        this.dispose();

    }//GEN-LAST:event_btnHabilitarSillaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHabilitarSilla;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtARazon;
    private javax.swing.JTextField txtNumeroSilla;
    // End of variables declaration//GEN-END:variables
}
